on: release
name: Go Release Binaries  
jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        # OS target: darwin, freebsd, linux, and so on
        goarch: amd64 
        sha256sum: TRUE
        overwrite: TRUE
    
